version: "3"
services:
    db:
        image: postgres:11-alpine
        container_name: db-nhacuadi
        # restart: unless-stopped
        restart: always
        hostname: postgres
        ports:
            - "6000:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: nhacuadi
        volumes:
            - ./postgres_data/dump:/tmp/dump
            - ./postgres_data/script:/docker-entrypoint-initdb.d
            - ./postgres_data/data:/data

    fastapi:
        container_name: backend-fastapi-nhacuadi
        command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python -B -m uvicorn app:app --reload --host 0.0.0.0 --port 8000'
        build:
            context: ./fastapi
            dockerfile: Dockerfile
        ports:
            - "6001:8000"
        volumes:
            - ./fastapi/app:/code/app
        environment:
            - POSTGRES_CONNECT_STRING=postgresql://postgres:postgres@db:5432/nhacuadi
        depends_on:
            - db

volumes:
    postgres_data:
    fastapi:
